export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const OTP_SENT = "OTP_SENT";
export const OTP_FAIL = "OTP_FAIL";
export const RETRY_OTP = "RETRY_OTP";
export const VERIFY_OTP = "VERIFY_OTP";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGOUT = "LOGOUT";

// platform Context

export const FREQUENTLY_ACCESSED_CRED = "FREQUENTLY_ACCESSED_CRED";
export const CATEGORIZED_CREDENTIALS = "CATEGORIZED_CREDENTIALS";
export const CREDENTIALS_ADDED = "CREDENTIALS_ADDED";

export const OPEN_SNACKBAR = "OPEN_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
